github: action: Fix faillure benchmark job

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -88,7 +88,7 @@ jobs:
           echo "Checking out current preivous branch"
           git checkout -
     - name: Cargo Bench
-      run:  cargo bench --jobs 1 --bench bench -- --output-format bencher | tee output.txt
+      run:  cargo bench --jobs 1 --bench bench -- --output-format bencher | tee output.txt || { echo "Benchmark failed"; exit 1; }
     - name: Compare results & store cached results
       uses: benchmark-action/github-action-benchmark@v1.18.0
       with:
